### PR TITLE
fix typo in readme

### PR DESCRIPTION
**Pull request by innerout**

### CODE REVIEW

**Comment by shombando** [comment]
@innerout thanks for finding and fixing the typo, I appreciate the help!
For some reason, other parts of the document are also showing as modified so I can't merge from mobile, I'll merge it in soon. Thanks again!

**Comment by innerout** [comment]
Should I rebase the changes in master and update the PR ?

**Comment by shombando** [comment]
@innerout that'd be great, sorry I haven't gotten to it yet. Have been doing all merges from the phone. Thanks!

**Comment by innerout** [comment]
Rebased main branch

**Comment by shombando** [comment]
@innerout sorry this got overlooked for so long. I really appreciate you fixing issues. I've added a lot more information and packages if you're interested in checking it out.
Thanks again!

**Pull request merged**
